#
# Kernel makefile for DTV.
#

obj-$(CONFIG_NXDTV_TDMB_1CHIP_AV_ONLY)	+= tdmb_pri/

obj-$(CONFIG_NXDTV_TDMB_1CHIP_AV_TPEG)	+= tdmb_pri/

obj-$(CONFIG_NXDTV_TDMB_2CHIP_AV_TPEG)	+= tdmb_pri/
obj-$(CONFIG_NXDTV_TDMB_2CHIP_AV_TPEG)	+= tdmb_sec/

obj-$(CONFIG_NXDTV_ISDBT_ONESEG)	+= oneseg/
obj-$(CONFIG_NXDTV_ISDBT_FULLSEG)	+= fullseg/

