#
# Copyright 2009 Nexell Co.
#
# Makefile for the Nexell Sound
obj-$(CONFIG_SND_NXP_EC)			+= 	nxp-snd-pcm-ec.o nxp-snd-i2s-ec.o resample.o resample2.o \
										nxp-snd-null-ec.o nxp-snd-pcm-sync.o

obj-$(CONFIG_SND_NXP_EC_PDM_VIRT)	+= nxp-snd-pcm-virt.o nxp-snd-pdm-virt.o  nxp-snd-pdm-virt-record.o
obj-$(CONFIG_SND_NXP_EC_PDM_SPI)	+= nxp-snd-pdm-spi.o  nxp-snd-pdm-spi-record.o

nxp-snd-pcm-ec-objs					:= nxp-pcm-ec.o
nxp-snd-i2s-ec-objs					:= nxp-i2s-ec.o
nxp-snd-null-ec-objs 				:= nxp-null-ec.o
nxp-snd-pcm-sync-objs 				:= nxp-pcm-sync.o

nxp-snd-pcm-virt-objs				:= nxp-pcm-virt.o
nxp-snd-pdm-virt-objs				:= nxp-pdm-virt.o
nxp-snd-pdm-virt-record-objs 		:= nxp-pdm-virt-record.o

nxp-snd-pdm-spi-objs				:= nxp-pdm-spi.o
nxp-snd-pdm-spi-record-objs 		:= nxp-pdm-spi-record.o







