obj-$(CONFIG_FCI_8080) += \
	bbm.o \
	fc8080.o \
	fc8080_bb.o \
	fc8080_i2c.o \
	fc8080_isr.o \
	fc8080_ppi.o \
	fc8080_spi.o \
	fc8080_tun.o \
	fci_hal.o \
	fci_hpi.o \
	fci_oal.o \
	fci_ringbuffer.o \
	fci_tun.o \
	fic.o \
	ficdecoder.o \
	platform.o

EXTRA_CFLAGS += -Idrivers/misc/fc8080/include
