##########################################
# Makefile for NXB220 Device Drivers.
##########################################
ccflags-y += -Idrivers/misc/nxdtv/fullseg
ccflags-y += -Idrivers/misc/nxdtv/fullseg/src

obj-y += nxb220.o
obj-y += nxb220_demod.o
obj-y += nxb220_rf.o
obj-y += nxb220_port.o

