#
# Copyright 2009 Nexell Co.
#
# Makefile for the Nexell Sound
obj-$(CONFIG_SND_NEXELL_SOC)	  += nxp-snd-pcm.o
obj-$(CONFIG_SND_NEXELL_I2S)	  += nxp-snd-i2s.o
obj-$(CONFIG_SND_NEXELL_SPDIF_TX) += nxp-snd-spdiftx.o
obj-$(CONFIG_SND_NEXELL_SPDIF_RX) += nxp-snd-spdifrx.o

nxp-snd-pcm-objs		:= nxp-pcm.o
nxp-snd-i2s-objs 		:= nxp-i2s.o
nxp-snd-spdiftx-objs	:= nxp-spdiftx.o
nxp-snd-spdifrx-objs	:= nxp-spdifrx.o

obj-$(CONFIG_SND_CODEC_NULL) 		+= nxp-snd-null.o
obj-$(CONFIG_SND_CODEC_RT5631)		+= nxp-snd-rt5631.o
obj-$(CONFIG_SND_CODEC_WM8976)		+= nxp-snd-wm8976.o
obj-$(CONFIG_SND_SPDIF_TRANSCIEVER)	+= nxp-snd-spdif-transciever.o
obj-$(CONFIG_SND_SPDIF_RECEIVER)	+= nxp-snd-spdif-receiver.o

nxp-snd-null-objs 					:= nxp-null.o
nxp-snd-rt5631-objs 				:= nxp-rt5631.o
nxp-snd-wm8976-objs 				:= nxp-wm8978.o
nxp-snd-spdif-transciever-objs 		:= nxp-spdif-transciever.o
nxp-snd-spdif-receiver-objs 		:= nxp-spdif-receiver.o



