##########################################
# Makefile for ISDBT NXB220 Device Drivers.
##########################################
ccflags-y += -Idrivers/misc/nxdtv/fullseg
ccflags-y += -Idrivers/misc/nxdtv/fullseg/src
#ccflags-y += -v

#ccflags-y += -D_ISDBT_DEVICE_TREE_UNUSED

obj-y := isdbt.o

# NXB220
obj-y += src/

# TSIF
obj-y += isdbt_i2c.o

