obj-$(CONFIG_V4L2_SLSI) 	+= nxp-v4l2.o nxp-v4l2-common.o nxp-video.o
obj-$(CONFIG_VIDEO_SLSI_CAPTURE) += capture/
obj-$(CONFIG_VIDEO_SLSI_M2M) += m2m/
obj-$(CONFIG_VIDEO_SLSI_OUT) += out/

EXTRA_CFLAGS += -Idrivers/media/video/nexell/capture \
				-Idrivers/media/video/nexell/m2m \
				-Idrivers/media/video/nexell/out
