#
# Kernel makefile for TDMB(NXB110)
#

EXTRA_CFLAGS += -I. -I./src

obj-y += mtv.o \
		mtv_spi.o \
		mtv_isr.o \
		./src/nxtv.o \
		./src/nxtv_port.o \
		./src/nxtv_rf.o \
		./src/nxtv_tdmb.o

