#
# Copyright 2009 Nexell Co.
#
# Makefile for the S5P4418

obj-y					:= board.o device.o
obj-$(CONFIG_SUSPEND)			+= pm.o
obj-$(CONFIG_ION_SLSI)			+= dev-ion.o
obj-$(CONFIG_USB_CONNECT_SLSI_DRV)	+= usb-connector.o

